[package]
name = "rs-exploit"
version = "0.1.0"
edition = "2021"

[build]
target = "x86_64-apple-darwin"

[lib]
crate_type = ["dylib"]
path = "src/main.rs"

[dependencies]
ctor = "0.1.26"
libc = { version = "0.2", features = ["std"] }
small_ctor = "0.1.0"
